src/MFER.App/ViewModels/ContatoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MFER.App.ViewModels;

public class ContatoViewModel
{
    public Guid Id { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório.")]
    [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
    public string Name { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório.")]
    [Display(Name = "E-mail")]
    public string Email { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório.")]
    public string Telefone { get; set; }
    
    public string? Mensagem { get; set; }
}

src/MFER.App/ViewModels/ErrorViewModel.cs
namespace MFER.App.ViewModels;

public class ErrorViewModel
{
    public string? Titulo { get; set; }
    public string? Mensagem { get; set; }
    public string? ErroCode { get; set; }
}

src/MFER.App/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MFER.App.Areas.Admin.Controllers;

[Area("Admin")]
[Route("home")]
public class HomeController : Controller
{
    [HttpGet("index")]
    public IActionResult Index()
    {
        return View();
    }
}

src/MFER.App/Components/CounterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MFER.App.Components;

/*Para a classe ser uma ViewComponent, ela precisa
 herdar de ViewComponent e implementar o método InvokeAsync
 */

public class CounterViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(int modelCounter)
    {
        return View(modelCounter);
    }
}

src/MFER.App/Controllers/HomeController.cs
using MFER.App.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MFER.App.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [Route("erro/{id:length(3,3)}")]
    public IActionResult Errors(int id)
    {
        var modelErro = new ErrorViewModel();

        if (id == 500)
        {
            modelErro.Mensagem = "Ocorreu um erro! Tente novamente mais tarde ou contate o nosso suporte!";
            modelErro.Titulo = "Ocorreu um erro!";
            modelErro.ErroCode = id.ToString();
        }
        else if (id == 404)
        {
            modelErro.Mensagem = "A página que está procurando não existe! <br />Em caso de dúvida !";
            modelErro.Titulo = "Ops! Página não encontrada!";
            modelErro.ErroCode = id.ToString();
        }
        else if (id == 403)
        {
            modelErro.Mensagem = "Você não tem permissão para fazer isso.";
            modelErro.Titulo = "Acesso negado";
            modelErro.ErroCode = id.ToString();
        }
        else
        {
            return StatusCode(500);
        }
        
        return View("Error", modelErro);
    }
}

src/MFER.App/Areas/Admin/Views/Home/Index.cshtml
<p>Testando areas!</p>

src/MFER.App/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <title>@ViewData["Title"] - Minha Aplicação</title>
        
        <enviroment include="Development"> 
            <!-- include="Development" = significa que todo ambiente que for Development ira carregar os links abaixo-->
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css"/>
            <link rel="stylesheet" href="~/css/site.css"/>
        </enviroment>
        
        <enviroment exclude="Development">
            <!-- include="Development" = significa que todo ambiente que não for Development ira carregar os links abaixo-->
        </enviroment>
    </head>
    <body>
    <header>
        <h1>Minha Aplicação</h1>
        <ul class="navbar-nav flex-grow-1 justify-content-center">
            <li class="nav-item">
                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                    Home
                </a>
            </li>
        </ul>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <p>&copy; 2024 - Minha Aplicação</p>
    </footer>
    <enviroment include="Development">
        <!-- include="Development" = significa que todo ambiente que for Development ira carregar os scripts abaixo-->
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
    </enviroment>

    <enviroment exclude="Development">
        <!-- include="Development" = significa que todo ambiente que não for Development ira carregar os scripts abaixo-->
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    </enviroment>
</body>
</html>

src/MFER.App/Views/Home/Index.cshtml
@page
@model MFER.App.Views.Index
Olá

<!--<vc:counter model-counter="5"></vc:counter>-->
@await Component.InvokeAsync("Counter", 5)

src/MFER.App/Views/Shared/Components/Counter/Default.cshtml
@model int

<div>
    <p>A consulta retornou @Model registro(s)</p>
</div>

src/MFER.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <title>@ViewData["Title"] - Minha Aplicação</title>
        
        <enviroment include="Development"> 
            <!-- include="Development" = significa que todo ambiente que for Development ira carregar os links abaixo-->
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css"/>
            <link rel="stylesheet" href="~/css/site.css"/>
        </enviroment>
        
        <enviroment exclude="Development">
            <!-- include="Development" = significa que todo ambiente que não for Development ira carregar os links abaixo-->
        </enviroment>
    </head>
    <body>
    <header>
        <h1>MFER</h1>
        <ul class="navbar-nav flex-grow-1 justify-content-center">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    About
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    My projects
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    My projects
                </a>
            </li>
        </ul>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <p>&copy; 2024 - Minha Aplicação</p>
    </footer>
    <enviroment include="Development">
        <!-- include="Development" = significa que todo ambiente que for Development ira carregar os scripts abaixo-->
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
    </enviroment>

    <enviroment exclude="Development">
        <!-- include="Development" = significa que todo ambiente que não for Development ira carregar os scripts abaixo-->
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    </enviroment>
</body>
</html>